let listDictionary = 
{
    //Name Website Title Business_name Birthrates Phone Location Zip?
    //////////////////////////////////
    //    DO NOT FORGET COMMAS
    //////////////////////////////////
    "A": {name: "Joy Thomas", business: "Postpartum Lifestyle, LLC", title: "Birth & Postpartum Doula", website: "https://www.postpartumlifestyle.com", location: "Greensboro, NC", phone: "336-355-7155", birthrate: "$600-$1500", postpartumrate: "$40/hr", zip: "27405", pic: "images/ppl.hs.JPG",},
    "B": {name: "Khalilah Moore", business: "KK Lact & Moore", title: "Birth & Postpartum Doula", website: "https://www.kklactandmoore.com", location: "Winston Salem, NC", phone: "kklactandmoore@yahoo.com", birthrate: "$600-$1000", postpartumrate: "contact for details", zip: "", pic: "images/kklactandmoore.jpg", },
    "C": {name: "Nkosazana Roper", business: "Ujima Village Care", title: "Postpartum Doula", website: "https://www.ujimavillagecare.com", location: "Rocky Mountain, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "D": {name: "A'myrah Bates", business: "Ase Doula Services", title: "Doula", website: "https://www.asedoulaservices.org", location: "Charlotte, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "E": {name: "Caitlin Clarke", business: "Caring for Legacies", title: "Doula", website: "n/a", location: "Charlotte, NC", phone: "caringforlegacies@gmail.com", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "F": {name: "", business: "Doula for Doula, LLC", title: "Doula", website: "n/a", location: "Charlotte, NC", phone: "prdoula@gmail.com", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "G": {name: "Leanna Davis", business: "Present Gift Doula", title: "Birth Doula", website: "https://www.brand.page/presentgiftdoula.com", location: "Charlotte, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "H": {name: "Denawa Deniece", business: "Q_City", title: "Doula", website: "https://www.qcitydoula.com", location: "Charlotte, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "I": {name: "Jajuana Moonie Crawley", business: "Doula Services", title: "Full Spectrum Doula", website: "https://www.jajuanamoonie.squarespace.com", location: "Charlotte, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "J": {name: "Kira Kimble", business: "Your Charlotte Doulas", title: "Doula", website: "https://yourcharlottedoulas.com", location: "Charlotte, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/",},
    "K": {name: "", business: "KK Lact & Moore", title: "Birth & Postpartum Doula", website: "https://www.kklactandmoore.com", location: "Winston Salem, NC", phone: "kklactandmoore@yahoo.com", birthrate: "$600-$1000", postpartumrate: "contact for details", zip: "", pic: "images/", },
    "L": {name: "", business: "Ujima Village Care", title: "Postpartum Doula", website: "https://www.ujimavillagecare.com", location: "Rocky Mountain, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "M": {name: "", business: "Ase Doula Services", title: "Doula", website: "https://www.asedoulaservices.org", location: "Charlotte, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "N": {name: "Caitlin Clarke", business: "Caring for Legacies", title: "Doula", website: "n/a", location: "Charlotte, NC", phone: "caringforlegacies@gmail.com", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "O": {name: "", business: "Doula for Doula, LLC", title: "Doula", website: "n/a", location: "Charlotte, NC", phone: "prdoula@gmail.com", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "P": {name: "", business: "Present Gift Doula", title: "Birth Doula", website: "https://www.brand.page/presentgiftdoula.com", location: "Charlotte, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "Q": {name: "", business: "Q_City", title: "Doula", website: "https://www.qcitydoula.com", location: "Charlotte, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},
    "R": {name: "Jajuana Moonie", business: "Doula Services", title: "Full Spectrum Doula", website: "https://www.jajuanamoonie.squarespace.com", location: "Charlotte, NC", phone: "via website", birthrate: "contact for details", postpartumrate: "contact for details", zip: "", pic: "images/program.png",},

}
